project_id = "akqllemasdhciqrckhok"

[functions.create-user]
verify_jwt = false

[functions.create-manager]
verify_jwt = false

[functions.manage-site]
verify_jwt = false

[functions.send-report]
verify_jwt = false
